export const TOGGLE_ISLOADING = 'TOGGLE_ISLOADING';
export const SAVE_PRODUCTS = 'SAVE_PRODUCTS';
export const UPDATE_MSG = 'UPDATE_MSG';
export const UPDATE_CART_MSG = 'UPDATE_CART_MSG';
export const SAVE_CART = 'SAVE_CART';
